version: '3.8'

services:
  kafka:
    image: apache/kafka:4.1.2
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      # ===== KRaft Core Config =====
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # ===== Listeners =====
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # IMPORTANT for dev
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      # ===== Cluster Config =====
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node

      # ===== Security (disabled for local dev) =====
      - xpack.security.enabled=false

      # ===== JVM Memory =====
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:

