spring.application.name=gateway
server.port=1000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Gateway routes
spring.cloud.gateway.routes[0].id=service-route
spring.cloud.gateway.routes[0].uri=lb://SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/service/**