spring.application.name=GATEWAY
server.port=1000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0
spring.cloud.gateway.routes[0].filters[1]=AddRequestHeader=X-Forwarded-Host,localhost

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com


public_key=${RS256_PUBLIC_KEY}

# Spring Security JWT checks
logging.level.org.springframework.security=DEBUG

# Incoming request handling
logging.level.org.springframework.web=DEBUG

# Gateway routing details
logging.level.org.springframework.cloud.gateway=TRACE

# JWT parsing/debugging
logging.level.io.jsonwebtoken=DEBUG